export const ADD_POST = 'ADD_POST'
export const ADD_POST_SUCCESSFULLY = `${ADD_POST}_SUCCESSFULLY`
export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_SUCCESSFULLY = `${GET_POSTS}_SUCCESSFULLY`

export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = `HIDE_LOADING`

export const UPLOAD_FILE = 'UPLOAD_FILE'
export const UPLOAD_FILE_SUCCESSFULLY = `UPLOAD_FILE_SUCCESSFULLY`

export const GET_ALL_MEDIA = 'GET_ALL_MEDIA'
export const GET_ALL_MEDIA_SUCCESSFULLY = `GET_ALL_MEDIA_SUCCESSFULLY`
