export const ADD_POST = 'ADD_POST'
export const ADD_POST_SUCCESSFULLY = `${ADD_POST}_SUCCESSFULLY`
export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_SUCCESSFULLY = `${GET_POSTS}_SUCCESSFULLY`
